[supervisord]
nodaemon=true
user=root

[program:flask_web]
command=gunicorn --bind 0.0.0.0:%(ENV_PORT)s --workers 2 flask_app.app:app
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:wialon_worker]
command=python -u wialon_background_worker/wialon.py
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0