"""adding table for registration with invitation token

Revision ID: a54f5ab3f734
Revises: 6f0fd935d0ec
Create Date: 2026-04-08 14:42:23.688854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a54f5ab3f734'
down_revision = '6f0fd935d0ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens_registro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tokens_registro'))
    )
    with op.batch_alter_table('tokens_registro', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tokens_registro_token'), ['token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tokens_registro', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tokens_registro_token'))

    op.drop_table('tokens_registro')
    # ### end Alembic commands ###
